service: aluc-io
frameworkVersion: ">=1.28.0"

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    includeModules: false
    webpackConfig: webpack.config.js
    packager: yarn

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:SLS_STAGE}
  region: ap-northeast-2
  memorySize: 128
  timeout: 2
  environment:
    SLS_BUCKET_NAME: ${env:SLS_BUCKET_NAME}
    CIRCLE_TAG: ${env:CIRCLE_TAG}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - "arn:aws:s3:::${env:SLS_BUCKET_NAME}"
        - "arn:aws:s3:::${env:SLS_BUCKET_NAME}/*"

functions:
  index:
    handler: handler.index
    events:
      - http:
          path: "/{proxy+}"
          method: get
