# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.15

version: 2
jobs:
  build_only:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: &yarn_install_build |
          yarn install
          yarn run build
      - save_cache: &save_cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  untagged_jobs:
    jobs:
      - build_only